name: CI Pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tải mã nguồn về Runner
        uses: actions/checkout@v3
      - name: Chạy script kiểm tra
        run: echo "Mã nguồn đã được tải thành công lên Ubuntu!"
