name: CI Pipeline
on:
  push:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tải mã nguồn về Runner
        uses: actions/checkout@v3
      - name: Chạy script kiểm tra
        run: echo "Mã nguồn đã được tải thành công lên Ubuntu!"
      - name: Kiểm tra Linter HTML (Kiểm tra thẻ title)
        run: |
          if grep -q "<title>" index.html; then
            echo "Linter Passed: Tồn tại thẻ title."
          else
            echo "Linter Failed: Thiếu thẻ title."
            exit 1
          fi
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy lên GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

